version: '2'

services:
  db:
    image: mysql:5
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: BrICiLIsOhREsmoRno
  web:
    build: .
    restart: always
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis
      MYSQL_ROOT_PASSWORD: BrICiLIsOhREsmoRno
    expose:
      - 3000
    networks:
      - traefik
      - default
    labels:
      traefik.enable: true
      traefik.docker.network: "traefik"
      traefik.port: 3000
      traefik.frontend.rule: Host:opinionate.sheth.io
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: 2628000
      traefik.frontend.headers.STSIncludeSubdomains: true
    depends_on:
      - db
      - redis
  redis:
    image: redis
    restart: always

volumes:
  db-data:

networks:
  traefik:
    external: true
