version: '2'

services:
  db:
    image: hsheth2/mysql-low-memory:5
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: BrICiLIsOhREsmoRno
  web:
    build: .
    restart: always
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis
      MYSQL_ROOT_PASSWORD: BrICiLIsOhREsmoRno
    expose:
      - 3000
    networks:
      - traefik
      - default
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.http.routers.opinionate-web.rule: Host(`opinionate.sheth.io`, `opinionate.ml`, `www.opinionate.ml`)
      traefik.http.routers.opinionate-web.tls: true
      traefik.http.routers.opinionate-web.middlewares: SecureTLS, opinionate-redirect
      traefik.http.middlewares.opinionate-redirect.redirectregex.regex: ^https?://(?:www.)?opinionate.ml/(.*)
      traefik.http.middlewares.opinionate-redirect.redirectregex.replacement: https://opinionate.sheth.io/$${1}
      traefik.http.middlewares.opinionate-redirect.redirectregex.permanent: true
    depends_on:
      - db
      - redis
  redis:
    image: redis
    restart: always

volumes:
  db-data:

networks:
  traefik:
    external: true
